# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/gvdr/src/Python/PickApex3D/PickApex3D.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PickApex3D(object):
    def setupUi(self, PickApex3D):
        PickApex3D.setObjectName("PickApex3D")
        PickApex3D.resize(987, 835)
        self.centralwidget = QtWidgets.QWidget(PickApex3D)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter_2.setLineWidth(10)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(10)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.display_frame = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.display_frame.sizePolicy().hasHeightForWidth())
        self.display_frame.setSizePolicy(sizePolicy)
        self.display_frame.setMinimumSize(QtCore.QSize(100, 200))
        self.display_frame.setAutoFillBackground(False)
        self.display_frame.setObjectName("display_frame")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Input = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Input.setObjectName("verticalLayout_Input")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_Input.addWidget(self.label)
        self.gridLayout_Protein = QtWidgets.QGridLayout()
        self.gridLayout_Protein.setObjectName("gridLayout_Protein")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_Protein.addWidget(self.label_2, 0, 0, 1, 1)
        self.NeutralMass = QtWidgets.QLineEdit(self.layoutWidget)
        self.NeutralMass.setObjectName("NeutralMass")
        self.gridLayout_Protein.addWidget(self.NeutralMass, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_Protein.addWidget(self.label_4, 0, 2, 1, 1)
        self.MinCS = QtWidgets.QLineEdit(self.layoutWidget)
        self.MinCS.setObjectName("MinCS")
        self.gridLayout_Protein.addWidget(self.MinCS, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_Protein.addWidget(self.label_3, 1, 0, 1, 1)
        self.MassAccuracy = QtWidgets.QLineEdit(self.layoutWidget)
        self.MassAccuracy.setObjectName("MassAccuracy")
        self.gridLayout_Protein.addWidget(self.MassAccuracy, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_Protein.addWidget(self.label_5, 1, 2, 1, 1)
        self.MaxCS = QtWidgets.QLineEdit(self.layoutWidget)
        self.MaxCS.setObjectName("MaxCS")
        self.gridLayout_Protein.addWidget(self.MaxCS, 1, 3, 1, 1)
        self.verticalLayout_Input.addLayout(self.gridLayout_Protein)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_Input.addWidget(self.label_6)
        self.gridLayout_CCS = QtWidgets.QGridLayout()
        self.gridLayout_CCS.setObjectName("gridLayout_CCS")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_CCS.addWidget(self.label_7, 0, 0, 1, 1)
        self.Calibration_a = QtWidgets.QLineEdit(self.layoutWidget)
        self.Calibration_a.setObjectName("Calibration_a")
        self.gridLayout_CCS.addWidget(self.Calibration_a, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_CCS.addWidget(self.label_8, 0, 3, 1, 1)
        self.Calibration_b = QtWidgets.QLineEdit(self.layoutWidget)
        self.Calibration_b.setObjectName("Calibration_b")
        self.gridLayout_CCS.addWidget(self.Calibration_b, 0, 4, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_CCS.addWidget(self.label_12, 0, 7, 1, 1)
        self.Calibration_X = QtWidgets.QLineEdit(self.layoutWidget)
        self.Calibration_X.setObjectName("Calibration_X")
        self.gridLayout_CCS.addWidget(self.Calibration_X, 0, 8, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_CCS.addWidget(self.label_9, 1, 0, 1, 2)
        self.TransferParam = QtWidgets.QLineEdit(self.layoutWidget)
        self.TransferParam.setObjectName("TransferParam")
        self.gridLayout_CCS.addWidget(self.TransferParam, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_CCS.addWidget(self.label_11, 1, 3, 1, 2)
        self.PusherDelay = QtWidgets.QLineEdit(self.layoutWidget)
        self.PusherDelay.setObjectName("PusherDelay")
        self.gridLayout_CCS.addWidget(self.PusherDelay, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_CCS.addWidget(self.label_10, 1, 6, 1, 3)
        self.Gas_mass = QtWidgets.QLineEdit(self.layoutWidget)
        self.Gas_mass.setObjectName("Gas_mass")
        self.gridLayout_CCS.addWidget(self.Gas_mass, 1, 9, 1, 1)
        self.verticalLayout_Input.addLayout(self.gridLayout_CCS)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Output_Data = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Output_Data.setRowCount(10)
        self.Output_Data.setColumnCount(2)
        self.Output_Data.setObjectName("Output_Data")
        self.Output_Data.horizontalHeader().setVisible(True)
        self.Output_Data.verticalHeader().setVisible(True)
        self.horizontalLayout.addWidget(self.Output_Data)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.selectSeries = QtWidgets.QSpinBox(self.layoutWidget1)
        self.selectSeries.setEnabled(False)
        self.selectSeries.setMinimum(0)
        self.selectSeries.setMaximum(0)
        self.selectSeries.setObjectName("selectSeries")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.selectSeries)
        self.horizontalLayout.addLayout(self.formLayout)
        self.Output_Series = QtWidgets.QTableWidget(self.layoutWidget1)
        self.Output_Series.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Output_Series.setRowCount(7)
        self.Output_Series.setColumnCount(2)
        self.Output_Series.setObjectName("Output_Series")
        self.Output_Series.horizontalHeader().setVisible(False)
        self.Output_Series.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.Output_Series)
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        PickApex3D.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PickApex3D)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        PickApex3D.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PickApex3D)
        self.statusbar.setObjectName("statusbar")
        PickApex3D.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(PickApex3D)
        self.toolBar.setObjectName("toolBar")
        PickApex3D.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Data_File = QtWidgets.QAction(PickApex3D)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoad_Data_File.setIcon(icon)
        self.actionLoad_Data_File.setObjectName("actionLoad_Data_File")
        self.actionSave_processed = QtWidgets.QAction(PickApex3D)
        icon = QtGui.QIcon.fromTheme("document-save")
        self.actionSave_processed.setIcon(icon)
        self.actionSave_processed.setObjectName("actionSave_processed")
        self.actionQuit = QtWidgets.QAction(PickApex3D)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionQuit.setIcon(icon)
        self.actionQuit.setObjectName("actionQuit")
        self.actionNext_series = QtWidgets.QAction(PickApex3D)
        self.actionNext_series.setObjectName("actionNext_series")
        self.actionPrevious_series = QtWidgets.QAction(PickApex3D)
        self.actionPrevious_series.setObjectName("actionPrevious_series")
        self.menuFile.addAction(self.actionLoad_Data_File)
        self.menuFile.addAction(self.actionSave_processed)
        self.menuFile.addAction(self.actionQuit)
        self.menuAction.addAction(self.actionNext_series)
        self.menuAction.addAction(self.actionPrevious_series)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.toolBar.addAction(self.actionLoad_Data_File)
        self.toolBar.addAction(self.actionSave_processed)
        self.toolBar.addSeparator()

        self.retranslateUi(PickApex3D)
        QtCore.QMetaObject.connectSlotsByName(PickApex3D)

    def retranslateUi(self, PickApex3D):
        _translate = QtCore.QCoreApplication.translate
        PickApex3D.setWindowTitle(_translate("PickApex3D", "Mobility Data Display"))
        self.label.setText(_translate("PickApex3D", "Protein selection"))
        self.label_2.setText(_translate("PickApex3D", "Neutral mass"))
        self.NeutralMass.setText(_translate("PickApex3D", "22952"))
        self.label_4.setText(_translate("PickApex3D", "Minimal charge state"))
        self.MinCS.setText(_translate("PickApex3D", "1"))
        self.label_3.setText(_translate("PickApex3D", "Mass accuracy (ppm)"))
        self.MassAccuracy.setText(_translate("PickApex3D", "200"))
        self.label_5.setText(_translate("PickApex3D", "Maximal charge state"))
        self.MaxCS.setText(_translate("PickApex3D", "50"))
        self.label_6.setText(_translate("PickApex3D", "CCS Calibration parameters"))
        self.label_7.setText(_translate("PickApex3D", "a"))
        self.Calibration_a.setText(_translate("PickApex3D", "231.7"))
        self.label_8.setText(_translate("PickApex3D", "b"))
        self.Calibration_b.setText(_translate("PickApex3D", "118.7"))
        self.label_12.setText(_translate("PickApex3D", "X"))
        self.Calibration_X.setText(_translate("PickApex3D", "0.6262"))
        self.label_9.setText(_translate("PickApex3D", "C"))
        self.TransferParam.setText(_translate("PickApex3D", "1.41"))
        self.label_11.setText(_translate("PickApex3D", "Pusher rate (µs)"))
        self.PusherDelay.setText(_translate("PickApex3D", "110"))
        self.label_10.setText(_translate("PickApex3D", "Gas mass"))
        self.Gas_mass.setText(_translate("PickApex3D", "28"))
        self.label_13.setText(_translate("PickApex3D", "Current series"))
        self.menuFile.setTitle(_translate("PickApex3D", "Fi&le"))
        self.menuAction.setTitle(_translate("PickApex3D", "Action"))
        self.toolBar.setWindowTitle(_translate("PickApex3D", "toolBar"))
        self.actionLoad_Data_File.setText(_translate("PickApex3D", "&Load Data File"))
        self.actionLoad_Data_File.setToolTip(_translate("PickApex3D", "Load "))
        self.actionLoad_Data_File.setShortcut(_translate("PickApex3D", "Ctrl+O"))
        self.actionSave_processed.setText(_translate("PickApex3D", "&Save processed"))
        self.actionSave_processed.setToolTip(_translate("PickApex3D", "Save the processed data"))
        self.actionSave_processed.setShortcut(_translate("PickApex3D", "Ctrl+S"))
        self.actionQuit.setText(_translate("PickApex3D", "&Quit"))
        self.actionQuit.setToolTip(_translate("PickApex3D", "Quit program without saving"))
        self.actionQuit.setShortcut(_translate("PickApex3D", "Ctrl+Q"))
        self.actionNext_series.setText(_translate("PickApex3D", "&Next series"))
        self.actionNext_series.setToolTip(_translate("PickApex3D", "Choose next series"))
        self.actionNext_series.setShortcut(_translate("PickApex3D", "Alt+N"))
        self.actionPrevious_series.setText(_translate("PickApex3D", "&Previous series"))
        self.actionPrevious_series.setToolTip(_translate("PickApex3D", "Select previous series"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PickApex3D = QtWidgets.QMainWindow()
    ui = Ui_PickApex3D()
    ui.setupUi(PickApex3D)
    PickApex3D.show()
    sys.exit(app.exec_())

